### ISSUE TITLE
clarifying source of Clarity added variables?

### ISSUE THREAD

**Issue by nickeubank** [MIDS-at-Duke/duke-social-distancing-survey#2]
@danclarity any chance I could ask you to provide a paragraph on the variables at the bottom of our survey? (sex, age, race, clarity, etc. etc.)?

**Comment by danclarity** [comment]
Sure-
Age and gender are supplied by the respondent. 
Race is provided here as both self-reported, and for those that match back to a voter file record, based on reporting by the SoS. (NC has self-reported race for many voters since it was a former VRA state.)
The Clarity scores are models we build ourselves to predict the likelihood of a registered voter to do a number of things, including likelihood to self-ID as a Democrat (party), turn out to vote in 2020, have a college degree, support abortion rights, attend church, and prioritize fighting climate change.  Except for college, none of these questions were directly asked of respondents and are purely probabilistic estimates for that individual. For example, 32% of those that are very likely to regularly attend church had been in a group with > 20 people in the last week, compared to only 16% for those that are least likely to attend church.
Phone type is the method of which we contacted that respondent, either IVR to a landline or a live caller to a cell phone.
Voter file matched is whether or not were were able to match that respondent back to a voter file record, and gives a reasonable estimate of whether or not that person is registered to vote.
